version: '3.6'
services:
  database:
    image: postgres:12.1

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file: .dev_env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@database