name: Rails Tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: Install PostgreSQL 12 client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Build App
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rails db:setup

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432
          RAILS_ENV: test
        run: |
        bundle exec rake test